/**
 * End-to-end test against the committed sample bag (public/sample-bags/tour.mcap).
 *
 * Exercises the unified entry in src/parsers/core.ts: format detection +
 * dispatch + the actual MCAP reader. The sample bag is generated by
 * scripts/build-sample-bag.mjs and committed, so a fresh checkout has
 * everything this suite needs.
 */

import { describe, it, expect, beforeEach, afterAll } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import {
  parseBag,
  readDeserializedMessages,
  readMessageAtTime,
  detectFormat,
  disposeParserCaches,
} from '../../src/parsers/core';
import { createFileSource } from '../../src/parsers/source';

const SAMPLE_PATH = join(process.cwd(), 'public', 'sample-bags', 'tour.mcap');
const SAMPLE_AVAILABLE = existsSync(SAMPLE_PATH);

function sampleSource() {
  const bytes = readFileSync(SAMPLE_PATH);
  return createFileSource(new File([new Uint8Array(bytes)], 'tour.mcap'));
}

beforeEach(() => disposeParserCaches());
afterAll(() => disposeParserCaches());

const describeWithSample = SAMPLE_AVAILABLE ? describe : describe.skip;

describeWithSample('integration/tour.mcap - detectFormat + parseBag', () => {
  it('detects MCAP format from the .mcap extension', async () => {
    expect(await detectFormat(sampleSource())).toBe('mcap');
  });

  it('reports every topic the synthesizer writes', async () => {
    const summary = await parseBag(sampleSource());
    expect(summary.format).toBe('mcap');
    expect(summary.fileName).toBe('tour.mcap');

    // scripts/build-sample-bag.mjs writes exactly these ten topics.
    const expected = new Set([
      '/odom',
      '/imu/data',
      '/scan',
      '/tf',
      '/markers',
      '/map',
      '/gps/fix',
      '/camera/image_raw',
      '/camera/camera_info',
      '/camera_rear/camera_info',
    ]);
    const names = new Set(summary.topics.map((t) => t.name));
    for (const name of expected) {
      expect(names.has(name), `missing topic ${name}`).toBe(true);
    }
  });

  it('reports the schema names with ROS2-style /msg/ separators', async () => {
    const summary = await parseBag(sampleSource());
    const byName = new Map(summary.topics.map((t) => [t.name, t.type]));
    expect(byName.get('/odom')).toBe('nav_msgs/msg/Odometry');
    expect(byName.get('/imu/data')).toBe('sensor_msgs/msg/Imu');
    expect(byName.get('/scan')).toBe('sensor_msgs/msg/LaserScan');
    expect(byName.get('/tf')).toBe('tf2_msgs/msg/TFMessage');
    expect(byName.get('/markers')).toBe('visualization_msgs/msg/MarkerArray');
    expect(byName.get('/map')).toBe('nav_msgs/msg/OccupancyGrid');
    expect(byName.get('/gps/fix')).toBe('sensor_msgs/msg/NavSatFix');
  });

  it('reports a ~30 s duration matching the synthesizer', async () => {
    const summary = await parseBag(sampleSource());
    // The synth runs over 30 seconds. Allow ±5% so refactors to the
    // synth don't accidentally invalidate the integration assert.
    expect(summary.duration).toBeGreaterThan(28);
    expect(summary.duration).toBeLessThan(32);
  });

  it('reports approximately the right per-topic frequencies', async () => {
    const summary = await parseBag(sampleSource());
    const byName = new Map(summary.topics.map((t) => [t.name, t.frequency]));
    // Synth Hz values: odom=10, imu=50, scan=10, tf=10, markers=1, map=0.5, gps=1.
    // Loose tolerance for the (N-1)/N off-by-one in the frequency formula.
    expect(byName.get('/imu/data')).toBeGreaterThan(30);
    expect(byName.get('/imu/data')).toBeLessThan(70);
    expect(byName.get('/odom')).toBeGreaterThan(8);
    expect(byName.get('/odom')).toBeLessThan(15);
    expect(byName.get('/markers')).toBeGreaterThan(0);
    expect(byName.get('/markers')).toBeLessThan(2);
  });
});

describeWithSample('integration/tour.mcap - message reads', () => {
  it('decodes Odometry messages with the expected pose shape', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const decoded = await readDeserializedMessages(source, summary.format, '/odom', 5);
    expect(decoded.length).toBeGreaterThan(0);
    const first = decoded[0].value as Record<string, unknown>;
    expect(first.header).toBeDefined();
    const pose = (first.pose as { pose: { position: { x: number; y: number } } }).pose;
    expect(typeof pose.position.x).toBe('number');
    expect(typeof pose.position.y).toBe('number');
  });

  it('preserves sub-second nanosec in header stamps', async () => {
    // The generator must write the ROS2 field name `nanosec`. A `nsec` field
    // name is silently dropped by MessageWriter (unknown numeric fields
    // encode as 0), which would quantize every stamp to whole seconds.
    const source = sampleSource();
    const summary = await parseBag(source);
    const decoded = await readDeserializedMessages(source, summary.format, '/odom', 3);
    expect(decoded.length).toBeGreaterThan(1);
    const stamps = decoded.map(
      (m) =>
        (m.value as { header: { stamp: { sec: number; nanosec: number } } }).header.stamp,
    );
    // /odom publishes at 10 Hz, so early messages share a second but must
    // carry distinct, non-zero sub-second parts.
    expect(stamps.some((s) => s.nanosec !== 0)).toBe(true);
    expect(new Set(stamps.map((s) => `${s.sec}.${s.nanosec}`)).size).toBe(stamps.length);
  });

  it('returns the message nearest to the midpoint of the bag', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const mid = summary.startTime + (summary.endTime - summary.startTime) / 2n;
    const message = await readMessageAtTime(source, summary.format, '/odom', mid);
    expect(message).not.toBeNull();
    expect(message!.timestamp >= summary.startTime).toBe(true);
    expect(message!.timestamp <= summary.endTime).toBe(true);
  });

  it('decodes a MarkerArray with the expected primitive types', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const decoded = await readDeserializedMessages(source, summary.format, '/markers', 1);
    expect(decoded.length).toBeGreaterThan(0);
    const first = decoded[0].value as { markers: Array<{ type: number; ns: string }> };
    expect(Array.isArray(first.markers)).toBe(true);
    expect(first.markers.length).toBeGreaterThan(0);
    // The synth writes markers in two namespaces ("status" and "planning").
    const namespaces = new Set(first.markers.map((m) => m.ns));
    expect(namespaces.has('status')).toBe(true);
    expect(namespaces.has('planning')).toBe(true);
  });

  it('decodes the OccupancyGrid header with the configured map dimensions', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const decoded = await readDeserializedMessages(source, summary.format, '/map', 1);
    expect(decoded.length).toBeGreaterThan(0);
    const first = decoded[0].value as { info: { width: number; height: number; resolution: number } };
    expect(first.info.width).toBe(200);
    expect(first.info.height).toBe(200);
    expect(first.info.resolution).toBeCloseTo(0.2, 3);
  });

  it('decodes a NavSatFix anchored around the configured lat/lon', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const decoded = await readDeserializedMessages(source, summary.format, '/gps/fix', 1);
    expect(decoded.length).toBeGreaterThan(0);
    const first = decoded[0].value as { latitude: number; longitude: number };
    // Cambridge UK around (52.20, 0.11) per the synth config.
    expect(first.latitude).toBeGreaterThan(52);
    expect(first.latitude).toBeLessThan(53);
    expect(first.longitude).toBeGreaterThan(0);
    expect(first.longitude).toBeLessThan(1);
  });
});

describeWithSample('integration/tour.mcap - error handling', () => {
  it('rejects unsupported formats with a specific message', async () => {
    // Build a tiny "fake" source whose magic bytes don't match anything we know.
    const garbage = new Uint8Array(64);
    for (let i = 0; i < garbage.length; i++) garbage[i] = i;
    const source = createFileSource(new File([garbage], 'mystery.unknown'));
    await expect(parseBag(source)).rejects.toThrow(/Unsupported file format/);
  });
});

describeWithSample('integration/tour.mcap - the demo story', () => {
  async function messages(topic: string, limit = 100000) {
    const source = sampleSource();
    const summary = await parseBag(source);
    return readDeserializedMessages(source, summary.format, topic, limit);
  }

  it('carries the new topics with their types', async () => {
    const summary = await parseBag(sampleSource());
    const byName = new Map(summary.topics.map((t) => [t.name, t.type]));
    expect(byName.get('/lidar/points')).toBe('sensor_msgs/msg/PointCloud2');
    expect(byName.get('/detections')).toBe('vision_msgs/msg/Detection2DArray');
    expect(byName.get('/detections_3d')).toBe('vision_msgs/msg/Detection3DArray');
    expect(byName.get('/robot/mode')).toBe('std_msgs/msg/String');
    expect(byName.get('/battery')).toBe('sensor_msgs/msg/BatteryState');
    expect(byName.get('/rosout')).toBe('rcl_interfaces/msg/Log');
    expect(byName.get('/plan')).toBe('nav_msgs/msg/Path');
    expect(byName.get('/particles')).toBe('geometry_msgs/msg/PoseArray');
  });

  it('the point cloud has xyz plus intensity and thousands of points per sweep', async () => {
    const [first] = await messages('/lidar/points', 1);
    const cloud = first!.value as { fields: Array<{ name: string }>; width: number; point_step: number; data: Uint8Array; header: { frame_id: string } };
    expect(cloud.fields.map((f) => f.name)).toEqual(['x', 'y', 'z', 'intensity', 'ring']);
    expect(cloud.header.frame_id).toBe('lidar_link');
    expect(cloud.width).toBeGreaterThan(1500);
    expect(cloud.data.byteLength).toBe(cloud.width * cloud.point_step);
  });

  it('the robot passes through every mode, in order, ending in RETURNING', async () => {
    const modes = (await messages('/robot/mode')).map((m) => (m.value as { data: string }).data);
    const runs = modes.filter((m, i) => i === 0 || m !== modes[i - 1]);
    expect(runs).toEqual(['IDLE', 'EXPLORING', 'AVOIDING', 'EXPLORING', 'AVOIDING', 'RETURNING']);
  });

  it('the battery falls below 20% exactly once, late in the run, and a warning says so', async () => {
    const battery = (await messages('/battery')).map((m) => (m.value as { percentage: number }).percentage);
    const crossings = battery.filter((p, i) => i > 0 && battery[i - 1]! >= 0.2 && p < 0.2);
    expect(crossings).toHaveLength(1);
    expect(battery.findIndex((p) => p < 0.2)).toBeGreaterThan(battery.length * 0.8);
    const logs = (await messages('/rosout')).map((m) => m.value as { level: number; msg: string });
    expect(logs.some((l) => l.level === 30 && /Battery at 20%/.test(l.msg))).toBe(true);
    expect(logs.some((l) => l.level === 40)).toBe(true);
  });

  it('detections are boxes for cars and people with scores, stamped like the image they describe', async () => {
    const dets = await messages('/detections');
    const images = await messages('/camera/image_raw');
    const all = dets.flatMap((d) => (d.value as { detections: Array<{ results: Array<{ hypothesis: { class_id: string; score: number } }>; bbox: { size_x: number; size_y: number } }> }).detections);
    expect(all.length).toBeGreaterThan(20);
    const classes = new Set(all.map((d) => d.results[0]!.hypothesis.class_id));
    expect([...classes].sort()).toEqual(['car', 'person']);
    for (const d of all) {
      expect(d.results[0]!.hypothesis.score).toBeGreaterThan(0.5);
      expect(d.results[0]!.hypothesis.score).toBeLessThanOrEqual(1);
      expect(d.bbox.size_x).toBeGreaterThan(0);
    }
    const stamp = (m: { value: unknown }) => {
      const s = (m.value as { header: { stamp: { sec: number; nanosec: number } } }).header.stamp;
      return `${s.sec}.${s.nanosec}`;
    };
    expect(dets.map(stamp)).toEqual(images.map(stamp));
  });

  it('3D detections are map-frame boxes of plausible size, with LiDAR returns on them', async () => {
    const dets = await messages('/detections_3d');
    const clouds = await messages('/lidar/points');
    type Box = { results: Array<{ hypothesis: { class_id: string } }>; bbox: { center: { position: { x: number; y: number; z: number } }; size: { x: number; y: number; z: number } } };
    const all = dets.flatMap((d) => (d.value as { detections: Box[] }).detections);
    expect(all.length).toBeGreaterThan(10);
    expect(new Set(all.map((b) => b.results[0]!.hypothesis.class_id))).toEqual(new Set(['car', 'person']));
    for (const b of all) {
      const { x, y, z } = b.bbox.size;
      expect(Math.min(x, y, z)).toBeGreaterThan(0.2);
      expect(Math.max(x, y, z)).toBeLessThan(8);
    }
    expect((dets[0]!.value as { header: { frame_id: string } }).header.frame_id).toBe('map');
    // Same cadence as the 2D detector, so a 3D box and a 2D box describe the same instant.
    const twoD = await messages('/detections');
    expect(dets.length).toBe(twoD.length);
    expect(clouds.length).toBeGreaterThan(0);
  });

  it('the map is revealed over time: more of it is known at the end than at the start', async () => {
    const maps = await messages('/map');
    const known = (m: { value: unknown }) => (m.value as { data: ArrayLike<number> }).data.length - Array.from((m.value as { data: ArrayLike<number> }).data).filter((c) => c === -1).length;
    expect(known(maps[maps.length - 1]!)).toBeGreaterThan(known(maps[0]!) * 3);
  });
});
