/**
 * End-to-end test against the committed sample bag (public/sample-bags/tour.mcap).
 *
 * Exercises the unified entry in src/parsers/core.ts: format detection +
 * dispatch + the actual MCAP reader. The sample bag is generated by
 * scripts/build-sample-bag.mjs and committed, so a fresh checkout has
 * everything this suite needs.
 */

import { describe, it, expect, beforeEach, afterAll } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import {
  parseBag,
  readDeserializedMessages,
  readMessageAtTime,
  detectFormat,
  disposeParserCaches,
} from '../../src/parsers/core';
import { createFileSource } from '../../src/parsers/source';

const SAMPLE_PATH = join(process.cwd(), 'public', 'sample-bags', 'tour.mcap');
const SAMPLE_AVAILABLE = existsSync(SAMPLE_PATH);

function sampleSource() {
  const bytes = readFileSync(SAMPLE_PATH);
  return createFileSource(new File([new Uint8Array(bytes)], 'tour.mcap'));
}

beforeEach(() => disposeParserCaches());
afterAll(() => disposeParserCaches());

const describeWithSample = SAMPLE_AVAILABLE ? describe : describe.skip;

describeWithSample('integration/tour.mcap — detectFormat + parseBag', () => {
  it('detects MCAP format from the .mcap extension', async () => {
    expect(await detectFormat(sampleSource())).toBe('mcap');
  });

  it('reports every topic the synthesizer writes', async () => {
    const summary = await parseBag(sampleSource());
    expect(summary.format).toBe('mcap');
    expect(summary.fileName).toBe('tour.mcap');

    // scripts/build-sample-bag.mjs writes exactly these seven topics.
    const expected = new Set([
      '/odom',
      '/imu/data',
      '/scan',
      '/tf',
      '/markers',
      '/map',
      '/gps/fix',
    ]);
    const names = new Set(summary.topics.map((t) => t.name));
    for (const name of expected) {
      expect(names.has(name), `missing topic ${name}`).toBe(true);
    }
  });

  it('reports the schema names with ROS2-style /msg/ separators', async () => {
    const summary = await parseBag(sampleSource());
    const byName = new Map(summary.topics.map((t) => [t.name, t.type]));
    expect(byName.get('/odom')).toBe('nav_msgs/msg/Odometry');
    expect(byName.get('/imu/data')).toBe('sensor_msgs/msg/Imu');
    expect(byName.get('/scan')).toBe('sensor_msgs/msg/LaserScan');
    expect(byName.get('/tf')).toBe('tf2_msgs/msg/TFMessage');
    expect(byName.get('/markers')).toBe('visualization_msgs/msg/MarkerArray');
    expect(byName.get('/map')).toBe('nav_msgs/msg/OccupancyGrid');
    expect(byName.get('/gps/fix')).toBe('sensor_msgs/msg/NavSatFix');
  });

  it('reports a ~30 s duration matching the synthesizer', async () => {
    const summary = await parseBag(sampleSource());
    // The synth runs over 30 seconds. Allow ±5% so refactors to the
    // synth don't accidentally invalidate the integration assert.
    expect(summary.duration).toBeGreaterThan(28);
    expect(summary.duration).toBeLessThan(32);
  });

  it('reports approximately the right per-topic frequencies', async () => {
    const summary = await parseBag(sampleSource());
    const byName = new Map(summary.topics.map((t) => [t.name, t.frequency]));
    // Synth Hz values: odom=10, imu=50, scan=10, tf=10, markers=1, map=0.5, gps=1.
    // Loose tolerance for the (N-1)/N off-by-one in the frequency formula.
    expect(byName.get('/imu/data')).toBeGreaterThan(30);
    expect(byName.get('/imu/data')).toBeLessThan(70);
    expect(byName.get('/odom')).toBeGreaterThan(8);
    expect(byName.get('/odom')).toBeLessThan(15);
    expect(byName.get('/markers')).toBeGreaterThan(0);
    expect(byName.get('/markers')).toBeLessThan(2);
  });
});

describeWithSample('integration/tour.mcap — message reads', () => {
  it('decodes Odometry messages with the expected pose shape', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const decoded = await readDeserializedMessages(source, summary.format, '/odom', 5);
    expect(decoded.length).toBeGreaterThan(0);
    const first = decoded[0].value as Record<string, unknown>;
    expect(first.header).toBeDefined();
    const pose = (first.pose as { pose: { position: { x: number; y: number } } }).pose;
    expect(typeof pose.position.x).toBe('number');
    expect(typeof pose.position.y).toBe('number');
  });

  it('returns the message nearest to the midpoint of the bag', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const mid = summary.startTime + (summary.endTime - summary.startTime) / 2n;
    const message = await readMessageAtTime(source, summary.format, '/odom', mid);
    expect(message).not.toBeNull();
    expect(message!.timestamp >= summary.startTime).toBe(true);
    expect(message!.timestamp <= summary.endTime).toBe(true);
  });

  it('decodes a MarkerArray with the expected primitive types', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const decoded = await readDeserializedMessages(source, summary.format, '/markers', 1);
    expect(decoded.length).toBeGreaterThan(0);
    const first = decoded[0].value as { markers: Array<{ type: number; ns: string }> };
    expect(Array.isArray(first.markers)).toBe(true);
    expect(first.markers.length).toBeGreaterThan(0);
    // The synth writes markers in two namespaces ("status" and "planning").
    const namespaces = new Set(first.markers.map((m) => m.ns));
    expect(namespaces.has('status')).toBe(true);
    expect(namespaces.has('planning')).toBe(true);
  });

  it('decodes the OccupancyGrid header with the configured map dimensions', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const decoded = await readDeserializedMessages(source, summary.format, '/map', 1);
    expect(decoded.length).toBeGreaterThan(0);
    const first = decoded[0].value as { info: { width: number; height: number; resolution: number } };
    expect(first.info.width).toBe(100);
    expect(first.info.height).toBe(100);
    expect(first.info.resolution).toBeCloseTo(0.1, 3);
  });

  it('decodes a NavSatFix anchored around the configured lat/lon', async () => {
    const source = sampleSource();
    const summary = await parseBag(source);
    const decoded = await readDeserializedMessages(source, summary.format, '/gps/fix', 1);
    expect(decoded.length).toBeGreaterThan(0);
    const first = decoded[0].value as { latitude: number; longitude: number };
    // Cambridge UK around (52.20, 0.11) per the synth config.
    expect(first.latitude).toBeGreaterThan(52);
    expect(first.latitude).toBeLessThan(53);
    expect(first.longitude).toBeGreaterThan(0);
    expect(first.longitude).toBeLessThan(1);
  });
});

describeWithSample('integration/tour.mcap — error handling', () => {
  it('rejects unsupported formats with a specific message', async () => {
    // Build a tiny "fake" source whose magic bytes don't match anything we know.
    const garbage = new Uint8Array(64);
    for (let i = 0; i < garbage.length; i++) garbage[i] = i;
    const source = createFileSource(new File([garbage], 'mystery.unknown'));
    await expect(parseBag(source)).rejects.toThrow(/Unsupported file format/);
  });
});
